// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC8Y4ig1pxqPXaBWsd5hwxnBjgjkTmGpk',
    appId: '1:750229581881:web:03ab581b292e08fa5bdde8',
    messagingSenderId: '750229581881',
    projectId: 'flutter-mvvm-bbs',
    authDomain: 'flutter-mvvm-bbs.firebaseapp.com',
    storageBucket: 'flutter-mvvm-bbs.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP9Zk3e6GwWfIkB5saXNnMqlBb6GeOcl8',
    appId: '1:750229581881:android:1c14c0bb3c5747bc5bdde8',
    messagingSenderId: '750229581881',
    projectId: 'flutter-mvvm-bbs',
    storageBucket: 'flutter-mvvm-bbs.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFUSngtwcTKONMALwjDwXHcG9MDejLNEE',
    appId: '1:750229581881:ios:73f817e5cd4e73955bdde8',
    messagingSenderId: '750229581881',
    projectId: 'flutter-mvvm-bbs',
    storageBucket: 'flutter-mvvm-bbs.appspot.com',
    iosBundleId: 'com.example.fluterMvvmBbs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFUSngtwcTKONMALwjDwXHcG9MDejLNEE',
    appId: '1:750229581881:ios:9857046176ac73975bdde8',
    messagingSenderId: '750229581881',
    projectId: 'flutter-mvvm-bbs',
    storageBucket: 'flutter-mvvm-bbs.appspot.com',
    iosBundleId: 'com.example.fluterMvvmBbs.RunnerTests',
  );
}
